# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/precise64"
  config.vm.define 'ubuntu' do |node|
    node.vm.hostname = 'ububtu.local'
    node.vm.provision "ansible" do |ansible|
        ansible.playbook = "main.yml"
      end
  end
end
